/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Luis
 * Created: 29 oct. 2021
 */

--Tabla provincia
CREATE TABLE PROVINCIA(

    NOMBRE VARCHAR(20) NOT NULL,
    PAIS VARCHAR(20),
    COMUNIDAD_AUTONOMA VARCHAR(20),

    CONSTRAINT NOMBRE_PK PRIMARY KEY(NOMBRE)
);
--Datos tabla provincia
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('ÁLAVA', 'ESPAÑA', 'PAÍS VASCO');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('ALBACETE', 'ESPAÑA', 'CASTILLA-LA MANCHA');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('ALICANTE', 'ESPAÑA', 'VALENCIA');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('ALMERIA', 'ESPAÑA','ANDALUCÍA');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('AVILA', 'ESPAÑA', 'CASTILLA Y LEÓN');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('BADAJOZ', 'ESPAÑA', 'EXTREMADURA');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('BALEARES', 'ESPAÑA', 'ISLAS BALEARES');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('BARCELONA', 'ESPAÑA', 'CATALUÑA');
INSERT INTO PROVINCIA (NOMBRE, PAIS, COMUNIDAD_AUTONOMA) VALUES ('MÁLAGA', 'ESPAÑA', 'ANDALUCÍA');

--Tabla persona
CREATE TABLE PERSONA(

    DNI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(20) NOT NULL,
    DIRECCION VARCHAR(50),
    LOCALIDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    TELEFONO INTEGER NOT NULL,

    CONSTRAINT DNI_PK PRIMARY KEY (DNI),
    CONSTRAINT PROVINCIA_PERSONA_FK FOREIGN KEY(PROVINCIA) REFERENCES PROVINCIA (NOMBRE)
);

--Tabla reserva_Habitacion
CREATE TABLE RESERVA_HABITACION(
    
    COD_HABITACION INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    FECHA_LLEGADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    REGIMEN VARCHAR(50) NOT NULL,
    NUMERO_HABITACIONES INTEGER NOT NULL,
    TIPO_HABITACION VARCHAR(50) NOT NULL,
    FUMADOR BOOLEAN,

    CONSTRAINT COD_HABITACION_PK PRIMARY KEY(COD_HABITACION),
    CONSTRAINT DNI_CLIENTE_HABITACION_FK FOREIGN KEY(DNI_CLIENTE) REFERENCES PERSONA (DNI)
);

--Tabla reserva_Salon
CREATE TABLE RESERVA_SALON(
    
    COD_SALON INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    TIPO_EVENTO VARCHAR(20) NOT NULL,
    NUM_PERSONAS INTEGER NOT NULL,
    TIPO_COCINA VARCHAR(50),
    FECHA_EVENTO DATE NOT NULL,
    HABITACIONES BOOLEAN,
    NUM_HABITACIONES INTEGER,
    NUM_DIAS INTEGER,
    CONSTRAINT COD_SALON_PK PRIMARY KEY(COD_SALON),
    CONSTRAINT DNI_CLIENTE_SALON_FK FOREIGN KEY(DNI_CLIENTE) REFERENCES PERSONA (DNI)
);